export const comment = {
    struct: {
        createdByAccount: "3obS9hbc4kATiYuqyHER4B1TuKfbtYC5JsL1FLKq5pjCTk7E",
        createdAtBlock: 825737,
        createdAtTime: 1644930612000,
        isUpdated: true,
        updatedByAccount: "3obS9hbc4kATiYuqyHER4B1TuKfbtYC5JsL1FLKq5pjCTk7E",
        updatedAtBlock: 825744,
        updatedAtTime: 1644930654000,
        contentId: "bafyreiapdwajc5dllc3nvusmngmxt4rj7btuns4rlwckjfcswsbdfw7w46",
        id: "513",
        ownerId: "3obS9hbc4kATiYuqyHER4B1TuKfbtYC5JsL1FLKq5pjCTk7E",
        hidden: false,
        rootPostId: "505",
        repliesCount: 0,
        hiddenRepliesCount: 0,
        visibleRepliesCount: 1,
        sharesCount: 0,
        upvotesCount: 1,
        downvotesCount: 0,
        score: 0,
        isRegularPost: false,
        isSharedPost: false,
        isComment: true,
    },
    id: "513",
    content: {
        body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        summary: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        isShowMore: false,
        id: "bafyreiapdwajc5dllc3nvusmngmxt4rj7btuns4rlwckjfcswsbdfw7w46",
    }
}

export const comments = [
    {
        struct: {
            createdByAccount: "3obS9hbc4kATiYuqyHER4B1TuKfbtYC5JsL1FLKq5pjCTk7E",
            createdAtBlock: 825737,
            createdAtTime: 1644930612000,
            isUpdated: true,
            updatedByAccount: "3obS9hbc4kATiYuqyHER4B1TuKfbtYC5JsL1FLKq5pjCTk7E",
            updatedAtBlock: 825744,
            updatedAtTime: 1644930654000,
            contentId: "bafyreiapdwajc5dllc3nvusmngmxt4rj7btuns4rlwckjfcswsbdfw7w4m",
            id: "511",
            ownerId: "3obS9hbc4kATiYuqyHER4B1TuKfbtYC5JsL1FLKq5pjCTk7E",
            hidden: false,
            rootPostId: "505",
            repliesCount: 0,
            hiddenRepliesCount: 0,
            visibleRepliesCount: 1,
            sharesCount: 0,
            upvotesCount: 0,
            downvotesCount: 0,
            score: 0,
            isRegularPost: false,
            isSharedPost: false,
            isComment: true,
        },
        id: "511",
        content: {
            body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
            summary: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
            isShowMore: false,
            id: "bafyreiapdwajc5dllc3nvusmngmxt4rj7btuns4rlwckjfcswsbdfw7w4m",
        }
    }, {
        struct: {
            createdByAccount: "3obS9hbc4kATiYuqyHER4B1TuKfbtYC5JsL1FLKq5pjCTk7E",
            createdAtBlock: 825737,
            createdAtTime: 1644930612000,
            isUpdated: true,
            updatedByAccount: "3obS9hbc4kATiYuqyHER4B1TuKfbtYC5JsL1FLKq5pjCTk7E",
            updatedAtBlock: 825744,
            updatedAtTime: 1644930654000,
            contentId: "bafyreiapdwajc5dllc3nvusmngmxt4rj7btuns4rlwckjfcswsbdfw7w46",
            id: "513",
            ownerId: "3obS9hbc4kATiYuqyHER4B1TuKfbtYC5JsL1FLKq5pjCTk7E",
            hidden: false,
            rootPostId: "505",
            repliesCount: 0,
            hiddenRepliesCount: 0,
            visibleRepliesCount: 0,
            sharesCount: 0,
            upvotesCount: 1,
            downvotesCount: 0,
            score: 0,
            isRegularPost: false,
            isSharedPost: false,
            isComment: true,
        },
        id: "513",
        content: {
            body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
            summary: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
            isShowMore: false,
            id: "bafyreiapdwajc5dllc3nvusmngmxt4rj7btuns4rlwckjfcswsbdfw7w46",
        }
    }
]

export const reply = {
    struct: {
        createdByAccount: "3q8bEXevGhtAXwqYGYwaeCY2qxGKnoUrQaz6MNvQGq8XLSqW",
        createdAtBlock: 837077,
        createdAtTime: 1644998652000,
        isUpdated: false,
        contentId: "bafyreie5mvqyob6rljtcxnbef5ip4zljglcw3oouw5ilj7afysyfatrwiq",
        id: "512",
        ownerId: "3q8bEXevGhtAXwqYGYwaeCY2qxGKnoUrQaz6MNvQGq8XLSqW",
        hidden: false,
        rootPostId: "505",
        parentId: "511",
        repliesCount: 0,
        hiddenRepliesCount: 0,
        visibleRepliesCount: 0,
        sharesCount: 0,
        upvotesCount: 0,
        downvotesCount: 0,
        score: 0,
        isRegularPost: false,
        isSharedPost: false,
        isComment: true,
    },
    id: "512",
    content: {
        body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        summary: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        isShowMore: false,
        id: "bafyreie5mvqyob6rljtcxnbef5ip4zljglcw3oouw5ilj7afysyfatrwiq",
    }
};
