export const post = {
    struct: {
        createdByAccount: "3s69FXMn5VyteGkQxmtaJkTvQDzH9BfxF8ev9qzHubZ8Ewzr",
        createdAtBlock: 825162,
        createdAtTime: 1644927162001,
        isUpdated: false,
        contentId: "bafyreiayilojn3dnzf3gr4oehlztd3xxzulhj2dg647o5b5s3db4k6wgqu",
        id: "505",
        ownerId: "3obS9hbc4kATiYuqyHER4B1TuKfbtYC5JsL1FLKq5pjCTk7E",
        hidden: false,
        spaceId: "1019",
        hiddenRepliesCount: 0,
        repliesCount: 2,
        sharesCount: 0,
        upvotesCount: 0,
        downvotesCount: 1,
        score: 0,
        isRegularPost: true,
        isSharedPost: false,
        isComment: false,
    },
    id: "505",
    content: {
        body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        image: "",
        tags: [],
        title: "Lorem Ipsum is simply dummy text of the printing",
        summary: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        isShowMore: false,
        id: "bafyreiayilojn3dnzf3gr4oehlztd3xxzulhj2dg647o5b5s3db4k6wgqu",
    }
};

export const sharedPost = {
    struct: {
        createdByAccount: "3s69FXMn5VyteGkQxmtaJkTvQDzH9BfxF8ev9qzHubZ8Ewzr",
        createdAtBlock: 825162,
        createdAtTime: 1644927162001,
        isUpdated: false,
        contentId: "bafyreiayilojn3dnzf3gr4oehlztd3xxzulhj2dg647o5b5s3db4k6wgqz",
        id: "506",
        ownerId: "3obS9hbc4kATiYuqyHER4B1TuKfbtYC5JsL1FLKq5pjCTk7E",
        hidden: false,
        spaceId: "1019",
        repliesCount: 1,
        hiddenRepliesCount: 0,
        sharesCount: 0,
        upvotesCount: 0,
        downvotesCount: 1,
        score: 0,
        isRegularPost: false,
        isSharedPost: true,
        isComment: false,
        originalPostId: "505"
    },
    id: "506",
    content: {
        body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        image: "",
        tags: [],
        title: "",
        summary: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isShowMore: false,
        id: "bafyreiayilojn3dnzf3gr4oehlztd3xxzulhj2dg647o5b5s3db4k6wgqz",
    }
};

export const hiddenPost = {
    struct: {
        createdByAccount: "3s69FXMn5VyteGkQxmtaJkTvQDzH9BfxF8ev9qzHubZ8Ewzr",
        createdAtBlock: 825162,
        createdAtTime: 1644927162001,
        isUpdated: false,
        contentId: "bafyreiayilojn3dnzf3gr4oehlztd3xxzulhj2dg647o5b5s3db4k6wgqd",
        id: "507",
        ownerId: "3s69FXMn5VyteGkQxmtaJkTvQDzH9BfxF8ev9qzHubZ8Ewzr",
        hidden: true,
        spaceId: "1019",
        repliesCount: 1,
        hiddenRepliesCount: 0,
        sharesCount: 1,
        upvotesCount: 0,
        downvotesCount: 1,
        score: 0,
        isRegularPost: true,
        isSharedPost: false,
        isComment: false,
    },
    id: "507",
    content: {
        body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        image: "",
        tags: [],
        title: "Lorem Ipsum is simply dummy text of the printing",
        summary: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        isShowMore: false,
        id: "bafyreiayilojn3dnzf3gr4oehlztd3xxzulhj2dg647o5b5s3db4k6wgqd",
    }
};

export const sharedHiddenPost = {
    struct: {
        createdByAccount: "3s69FXMn5VyteGkQxmtaJkTvQDzH9BfxF8ev9qzHubZ8Ewzr",
        createdAtBlock: 825162,
        createdAtTime: 1644927162001,
        isUpdated: false,
        contentId: "bafyreiayilojn3dnzf3gr4oehlztd3xxzulhj2dg647o5b5s3db4k6wgqa",
        id: "508",
        ownerId: "3obS9hbc4kATiYuqyHER4B1TuKfbtYC5JsL1FLKq5pjCTk7E",
        hidden: false,
        spaceId: "1019",
        hiddenRepliesCount: 0,
        repliesCount: 1,
        sharesCount: 0,
        upvotesCount: 0,
        downvotesCount: 1,
        score: 0,
        isRegularPost: false,
        isSharedPost: true,
        isComment: false,
        originalPostId: "507"
    },
    id: "508",
    content: {
        body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        image: "",
        tags: [],
        title: "",
        summary: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        isShowMore: false,
        id: "bafyreiayilojn3dnzf3gr4oehlztd3xxzulhj2dg647o5b5s3db4k6wgqa",
    }
};

export const postWithHiddenPost = {
    struct: {
        createdByAccount: "3s69FXMn5VyteGkQxmtaJkTvQDzH9BfxF8ev9qzHubZ8Ewzr",
        createdAtBlock: 825162,
        createdAtTime: 1644927162001,
        isUpdated: false,
        contentId: "bafyreiayilojn3dnzf3gr4oehlztd3xxzulhj2dg647o5b5s3db4k6w333",
        id: "600",
        ownerId: "3s69FXMn5VyteGkQxmtaJkTvQDzH9BfxF8ev9qzHubZ8Ewzr",
        hidden: false,
        spaceId: "1030",
        repliesCount: 2,
        hiddenRepliesCount: 0,
        sharesCount: 0,
        upvotesCount: 0,
        downvotesCount: 1,
        score: 0,
        isRegularPost: true,
        isSharedPost: false,
        isComment: false,
    },
    id: "600",
    content: {
        body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        image: "",
        tags: [],
        title: "Lorem Ipsum is simply dummy text of the printing",
        summary: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        isShowMore: false,
        id: "bafyreiayilojn3dnzf3gr4oehlztd3xxzulhj2dg647o5b5s3db4k6w333",
    }
}
