export { default as avatar } from '../../public/avatar.jpg'
export { default as avatarExample } from '../../public/avatar-example.jpg'
export { default as qr } from '../../public/qr.svg'
export { default as copyIco } from '../../public/icons/copy.svg'
export { default as img } from '../../public/img.jpg'
export { default as commentIco } from '../../public/icons/comment.svg'
export { default as post } from '../../public/post.jpg'
export { default as postPage } from '../../public/post-page.jpg'
export { default as mediumIco } from '../../public/icons/m.svg'
export { default as walletIco } from '../../public/icons/wallet.svg'
export {default as photoIco} from '../../public/icons/photo.svg'

export { default as medium } from '../../public/icons/social/medium.svg'
export { default as linkidIn } from '../../public/icons/social/linkedin.svg'
export { default as youtube } from '../../public/icons/social/youtube.svg'
export { default as telegram } from '../../public/icons/social/telegram.svg'
export { default as reddit } from '../../public/icons/social/reddit.svg'

export {default as google} from '../../public/icons/google.svg'
export {default as firefox} from '../../public/icons/firefox.svg'
